apiVersion: v1
kind: Service
metadata:
  name: no-selector-service1
  namespace: test-service-dev1
spec:
  ports:
    - name: TCP
      port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
