apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/part-of: test-dep
    test: help
  name: test-external-service-1
  namespace: test-service-dev1
spec:
  ports:
    - name: TCP
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s.cpaas.nutanix.com/app: test-dep
    k8s.cpaas.nutanix.com/deployment-name: test-dep
    k8s.cpaas.nutanix.com/product: test-service
    k8s.cpaas.nutanix.com/programming-language: golang
    k8s.cpaas.nutanix.com/team: team1
    k8s.cpaas.nutanix.com/workload-resource-type: general
  type: ClusterIP
